TrajectoryPlannerROS:
  sim_time: 0.5
  holonomic_rob: false
  meter_scoring: true
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  pdist_scale: 5.0
  controller_frequncy: 10

  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 1.5
  acc_lim_y: 1.5
